# CMake generated Testfile for 
# Source directory: F:/~dev/rawrxd
# Build directory: F:/~dev/_cfg_probe
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test("test_llama_native" "F:/~dev/_cfg_probe/tests/test_llama_native.exe")
set_tests_properties("test_llama_native" PROPERTIES  WORKING_DIRECTORY "F:/~dev/_cfg_probe/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16122;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
add_test("k2_runtime_validation" "F:/~dev/_cfg_probe/tests/k2_runtime_validation.exe")
set_tests_properties("k2_runtime_validation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/_cfg_probe/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16176;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
add_test("test_q4k_decoder" "F:/~dev/_cfg_probe/tests/test_q4k_decoder.exe")
set_tests_properties("test_q4k_decoder" PROPERTIES  WORKING_DIRECTORY "F:/~dev/_cfg_probe/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16188;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
add_test("k2_native_smoke_test" "F:/~dev/_cfg_probe/tests/k2_native_smoke_test.exe")
set_tests_properties("k2_native_smoke_test" PROPERTIES  WORKING_DIRECTORY "F:/~dev/_cfg_probe/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16247;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
add_test("k2_002_tensor_streaming" "F:/~dev/_cfg_probe/tests/k2_002_tensor_streaming.exe")
set_tests_properties("k2_002_tensor_streaming" PROPERTIES  WORKING_DIRECTORY "F:/~dev/_cfg_probe/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16298;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
add_test("k2_003_layer_execution" "F:/~dev/_cfg_probe/tests/k2_003_layer_execution.exe")
set_tests_properties("k2_003_layer_execution" PROPERTIES  WORKING_DIRECTORY "F:/~dev/_cfg_probe/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16349;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
add_test("k2_003b_native_gemv_validation" "F:/~dev/_cfg_probe/tests/k2_003b_native_gemv_validation.exe")
set_tests_properties("k2_003b_native_gemv_validation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/_cfg_probe/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16363;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
add_test("k2_003c_single_layer_forward" "F:/~dev/_cfg_probe/tests/k2_003c_single_layer_forward.exe")
set_tests_properties("k2_003c_single_layer_forward" PROPERTIES  WORKING_DIRECTORY "F:/~dev/_cfg_probe/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16377;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
add_test("k2_004_bounded_prefill" "F:/~dev/_cfg_probe/tests/k2_004_bounded_prefill.exe")
set_tests_properties("k2_004_bounded_prefill" PROPERTIES  WORKING_DIRECTORY "F:/~dev/_cfg_probe/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16428;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
add_test("k2_004_bounded_multi_layer_prefill" "F:/~dev/_cfg_probe/tests/k2_004_bounded_multi_layer_prefill.exe")
set_tests_properties("k2_004_bounded_multi_layer_prefill" PROPERTIES  WORKING_DIRECTORY "F:/~dev/_cfg_probe/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16442;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
add_test("k2_005_autoregressive_kv_cache" "F:/~dev/_cfg_probe/tests/k2_005_autoregressive_kv_cache.exe")
set_tests_properties("k2_005_autoregressive_kv_cache" PROPERTIES  WORKING_DIRECTORY "F:/~dev/_cfg_probe/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16457;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
add_test("k2_006_bounded_token_generation" "F:/~dev/_cfg_probe/tests/k2_006_bounded_token_generation.exe")
set_tests_properties("k2_006_bounded_token_generation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/_cfg_probe/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16472;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
add_test("k2_007_real_output_projection" "F:/~dev/_cfg_probe/tests/k2_007_real_output_projection.exe")
set_tests_properties("k2_007_real_output_projection" PROPERTIES  WORKING_DIRECTORY "F:/~dev/_cfg_probe/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16485;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
add_test("k2_007b_projection_logits_interface" "F:/~dev/_cfg_probe/tests/k2_007b_projection_logits_interface.exe")
set_tests_properties("k2_007b_projection_logits_interface" PROPERTIES  WORKING_DIRECTORY "F:/~dev/_cfg_probe/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16503;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
add_test("k2_008_end_to_end_semantic_generation" "F:/~dev/_cfg_probe/tests/k2_008_end_to_end_semantic_generation.exe")
set_tests_properties("k2_008_end_to_end_semantic_generation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/_cfg_probe/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16520;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
add_test("k2_009_token_embedding_lookup" "F:/~dev/_cfg_probe/tests/k2_009_token_embedding_lookup.exe")
set_tests_properties("k2_009_token_embedding_lookup" PROPERTIES  WORKING_DIRECTORY "F:/~dev/_cfg_probe/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16537;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
add_test("git_safety_authority_cert" "F:/~dev/_cfg_probe/bin/git_safety_authority_cert.exe")
set_tests_properties("git_safety_authority_cert" PROPERTIES  WORKING_DIRECTORY "F:/~dev/_cfg_probe" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;19121;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
add_test("refactor_chain_cert" "F:/~dev/_cfg_probe/bin/refactor_chain_cert.exe" "--fixture" "F:/~dev/rawrxd/audit/RAWRXD_P1_REFACTOR_CHAIN_001/fixture" "--out" "F:/~dev/rawrxd/audit/RAWRXD_P1_REFACTOR_CHAIN_001/RECEIPT.txt")
set_tests_properties("refactor_chain_cert" PROPERTIES  WORKING_DIRECTORY "F:/~dev/_cfg_probe" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;19321;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
subdirs("src/reverse_engineering")
subdirs("src/ceo")
subdirs("src/repository")
subdirs("src/generation")
subdirs("rguf_source")
