file(SHA256 "F:/~dev/rawrxd/src/deep2/Deep2Engine.h" H)
message(STATUS "FILE_SHA=[${H}]")
string(SHA256 "abc" S)
message(STATUS "STRING_SHA=[${S}]")
set(L a b c)
string(REPLACE ";" "\n" B "${L}")
message(STATUS "BLOB=[${B}]")
foreach(x IN LISTS L)
  message(STATUS "  iter=${x}")
endforeach()
